### ISSUE TITLE
error message while running the plugin

### ISSUE THREAD

**Issue by TeamMarsicano** [sommerc/napari-correct-drift#1] opened 2023-05-04 08:50 UTC
We are new to napari. We are trying to see if this plugin with help us to correct 3D drift in lattice light sheet images after deskewing and deconvolution. We are using napari GUI.
The error message is the following: array object has no attribute flags. Did we miss anything in the installation of the plugin? Is it because we do not have metadata attached to the stacks?
Thanks for making this plugin available for napari users.

**Comment by sommerc** [comment] 2023-05-05 09:54
Dear @TeamMarsicano,

thank you for your report. I think I found the issue. I created a new version, which you can install over [pip](https://pypi.org/project/napari-correct-drift/0.0.2/).

Let me know if it works now for you.

Cheers,
Chris

**Comment by sommerc** [comment] 2023-05-26 09:59
Did you already have a chance to try it again?

Cheers,
Chris

**Comment by TeamMarsicano** [comment] 2023-06-01 07:54
Hi Christoph.
Sorry for the late reply.
Yes, we tried and we got another error message. I do not remember what it
was exactly, but I can reproduce what we did next week to fw it to you. We
did not have time to figure it out, so we are not sure it does not come
from a problem on our side.
Best
Sandrine

**Comment by sommerc** [comment] 2023-06-01 08:25
Thanks you. If you could provide me with the excact error message, that would be great!

C

**Comment by sommerc** [comment] 2023-06-28 14:01
Closing this for now. Feel free to reopen in case the problem is not fully fixed for you.

C

**Comment by sommerc** [comment] 2023-06-28 14:02
Closing this for now. Feel free to reopen in case the problem is not fully fixed for you.

C

**Comment by sommerc** [comment] 2023-06-28 14:04
Feel free to reopen if issue is not solved for you.
C

**Comment by alemanac** [comment] 2023-10-17 01:40
Hi,

I'm new to running Napari and working with images in general, and I came across the same error that this user reported. Below are the exact steps to reproduce the error. Traceback error is below as well.

1. Open Napari through Anaconda 
2. File -> Open files as stacks
3. load two tif files of same dimensions
4. Plugins -> Napari Correct Drift Doc
5. Click image
6. ROI over an area of interest
7. -> Estimate drift
    1. ‘“Array' object has no attribute 'flags’”
8. -> Apply drift
    1. “’CorrectDriftDock' object has no attribute 'drift_table”

Please let me know if you need anything from me!

EDIT: I have been loading two (sometimes more) 3D images into a hyperstack. Is that permitted by the plugin?

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~\anaconda3\envs\napari\lib\site-packages\napari_correct_drift\_widget.py:422, in CorrectDriftDock.estimate_drift(self=<napari_correct_drift._widget.CorrectDriftDock object>)
    414     shape_poly = roi_layer.data[0]
    415     roi = ROIRect.from_shape_poly(
    416         shape_poly,
    417         self.CorrDrift.dims,
    418         z_min=self.roi_z_min.value(),
    419         z_max=self.roi_z_max.value(),
    420     )
--> 422 drift_shifts = self.CorrDrift.estimate_drift(
        self = <napari_correct_drift._widget.CorrectDriftDock object at 0x00000267D95D0B80>
        self.CorrDrift = <napari_correct_drift._core.CorrectDrift object at 0x0000026819D14100>
        key_frame = 0
        key_channel = 0
        increment = 1
        upsample_factor = 1
        roi = <napari_correct_drift._core.ROIRect object at 0x00000267E61409A0>
        estimate_mode = 'relative'
    423     t0=key_frame,
    424     channel=key_channel,
    425     increment=increment,
    426     upsample_factor=upsample_factor,
    427     roi=roi,
    428     mode=estimate_mode,
    429 )
    431 if increment > 1:
    432     drift_shifts = self.CorrDrift.interpolate_drift(drift_shifts)

File ~\anaconda3\envs\napari\lib\site-packages\napari_correct_drift\_core.py:386, in CorrectDrift.estimate_drift(self=<napari_correct_drift._core.CorrectDrift object>, t0=0, channel=0, increment=1, upsample_factor=1, roi=<napari_correct_drift._core.ROIRect object>, mode='relative')
    376 def estimate_drift(
    377     self,
    378     t0: int = 0,
   (...)
    383     mode: str = "relative",
    384 ):
    385     if mode == "relative":
--> 386         return self._estimate_drift_relative(
        self = <napari_correct_drift._core.CorrectDrift object at 0x0000026819D14100>
        t0 = 0
        channel = 0
        increment = 1
        upsample_factor = 1
        roi = <napari_correct_drift._core.ROIRect object at 0x00000267E61409A0>
    387             t0, channel, increment, upsample_factor, roi
    388         )
    390     elif mode == "absolute":
    391         return self._estimate_drift_absolute(
    392             t0, channel, increment, upsample_factor, roi
    393         )

File ~\anaconda3\envs\napari\lib\site-packages\napari_correct_drift\_core.py:454, in CorrectDrift._estimate_drift_relative(self=<napari_correct_drift._core.CorrectDrift object>, t0=0, channel=0, increment=1, upsample_factor=1, roi=<napari_correct_drift._core.ROIRect object>)
    449 with warnings.catch_warnings():
    450     warnings.filterwarnings(
    451         action="ignore",
    452         category=RuntimeWarning,
    453     )
--> 454     offset, _, _ = phase_cross_correlation(
        ref_img = dask.array<setitem, shape=(1, 512, 1206), dtype=float32, chunksize=(1, 512, 1206), chunktype=numpy.ndarray>
        mov_img = dask.array<getitem, shape=(1, 512, 1206), dtype=float32, chunksize=(1, 512, 1206), chunktype=numpy.ndarray>
        upsample_factor = 1
    455         ref_img,
    456         mov_img,
    457         upsample_factor=upsample_factor,
    458         return_error="always",
    459         disambiguate=True,
    460     )
    462 offset = np.asarray(offset, dtype="float32")
    464 if roi is not None:

File ~\anaconda3\envs\napari\lib\site-packages\skimage\registration\_phase_cross_correlation.py:331, in phase_cross_correlation(reference_image=dask.array<setitem, shape=(1, 512, 1206), dtype=...hunksize=(1, 512, 1206), chunktype=numpy.ndarray>, moving_image=dask.array<getitem, shape=(1, 512, 1206), dtype=...hunksize=(1, 512, 1206), chunktype=numpy.ndarray>, upsample_factor=1, space='real', disambiguate=True, return_error='always', reference_mask=None, moving_mask=None, overlap_ratio=0.3, normalization='phase')
    329 # real data needs to be fft'd.
    330 elif space.lower() == 'real':
--> 331     src_freq = fftn(reference_image)
        reference_image = dask.array<setitem, shape=(1, 512, 1206), dtype=float32, chunksize=(1, 512, 1206), chunktype=numpy.ndarray>
        fftn = <uarray multimethod 'fftn'>
    332     target_freq = fftn(moving_image)
    333 else:

File ~\anaconda3\envs\napari\lib\site-packages\scipy\fft\_backend.py:25, in _ScipyBackend.__ua_function__(method=<uarray multimethod 'fftn'>, args=(dask.array<setitem, shape=(1, 512, 1206), dtype=...hunksize=(1, 512, 1206), chunktype=numpy.ndarray>,), kwargs={})
     23 if fn is None:
     24     return NotImplemented
---> 25 return fn(*args, **kwargs)
        fn = functools.partial(<function c2cn at 0x00000267CB8AAB80>, True)
        args = (dask.array<setitem, shape=(1, 512, 1206), dtype=float32, chunksize=(1, 512, 1206), chunktype=numpy.ndarray>,)
        kwargs = {}

File ~\anaconda3\envs\napari\lib\site-packages\scipy\fft\_pocketfft\basic.py:180, in c2cn(forward=True, x=dask.array<setitem, shape=(1, 512, 1206), dtype=...hunksize=(1, 512, 1206), chunktype=numpy.ndarray>, s=None, axes=None, norm=None, overwrite_x=False, workers=None, plan=None)
    177 if plan is not None:
    178     raise NotImplementedError('Passing a precomputed plan is not yet '
    179                               'supported by scipy.fft functions')
--> 180 tmp = _asfarray(x)
        x = dask.array<setitem, shape=(1, 512, 1206), dtype=float32, chunksize=(1, 512, 1206), chunktype=numpy.ndarray>
    182 shape, axes = _init_nd_shape_and_axes(tmp, s, axes)
    183 overwrite_x = overwrite_x or _datacopied(tmp, x)

File ~\anaconda3\envs\napari\lib\site-packages\scipy\fft\_pocketfft\helper.py:97, in _asfarray(x=dask.array<setitem, shape=(1, 512, 1206), dtype=...hunksize=(1, 512, 1206), chunktype=numpy.ndarray>)
     95 dtype = x.dtype.newbyteorder('=')
     96 # Always align input
---> 97 copy = not x.flags['ALIGNED']
        x = dask.array<setitem, shape=(1, 512, 1206), dtype=float32, chunksize=(1, 512, 1206), chunktype=numpy.ndarray>
     98 return np.array(x, dtype=dtype, copy=copy)

AttributeError: 'Array' object has no attribute 'flags'`

**Comment by sommerc** [comment] 2023-10-17 11:35
Hi Tony,

thanks for the report. 

From the error msg it seems that your images are dask arrays. And this leads to problems in scipy.fft...

How do you open your images? With a specific image loader-plugin?

Cheers,
Chris

**Comment by alemanac** [comment] 2023-10-17 16:38
I opened the images (tif files) as a stack. I did this by going to File then Open Files as Stack. No plugin was used. 

Does that clear things up? Let me know if you need any additional info. The dimensions of the tif files are xyz. I believe this opens them up as a hyperstack, correct?

**Comment by sommerc** [comment] 2023-10-18 08:33
Thanks for the info. I found the issue. Napari uses dask-arrays when opening single images as stacks. This is not directly compatible with other functions I use...

I will fix it and make a new release very soon. Stay tuned! :-)

Cheers,
Chris

**Comment by sommerc** [comment] 2023-10-23 14:21
The latest release should fix the issue! 

Cheers,
Chris

**Comment by alemanac** [comment] 2023-10-23 18:41
Awesome! Thank you so much. I will check the release out and report back. Thanks again.

**Comment by alemanac** [comment] 2023-10-31 01:14
Hey Chris,

Sorry for getting back so late. Unfortunately, I ran into another error. I'll try tacking it on my end, but admittedly I am not the best programmer. Here's how to reproduce the error and the error itself:

1. Open Napari
2. Files -> open files as stack…
3. Load in four 3D tif files
4. Plugins -> napari correct 3D drift
5. Use ROI -> ROI over region of interest
6. Estimate drift -> error

error: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~\anaconda3\envs\napari\lib\site-packages\napari_correct_drift\_widget.py:541, in CorrectDriftDock.estimate_drift(self=<napari_correct_drift._widget.CorrectDriftDock object>)
    534 if self.handle_outlier.isChecked():
    535     max_shifts = (
    536         self.max_shift_z.value(),
    537         self.max_shift_y.value(),
    538         self.max_shift_x.value(),
    539     )
--> 541 drift_shifts = self.CorrDrift.estimate_drift(
        self = <napari_correct_drift._widget.CorrectDriftDock object at 0x000001A384B87C10>
        self.CorrDrift = <napari_correct_drift._core.CorrectDrift object at 0x000001A3DA01CFA0>
        key_frame = 0
        key_channel = 0
        increment = 1
        upsample_factor = 1
        roi = <napari_correct_drift._core.ROIRect object at 0x000001A3DA01CFD0>
        estimate_mode = 'relative'
        normalization = 'phase'
        max_shifts = None
    542     t0=key_frame,
    543     channel=key_channel,
    544     increment=increment,
    545     upsample_factor=upsample_factor,
    546     roi=roi,
    547     mode=estimate_mode,
    548     normalization=normalization,
    549     max_shifts=max_shifts,
    550 )
    552 if increment > 1 or np.any(np.isnan(drift_shifts)):
    553     drift_shifts = self.CorrDrift.interpolate_drift(drift_shifts)

File ~\anaconda3\envs\napari\lib\site-packages\napari_correct_drift\_core.py:391, in CorrectDrift.estimate_drift(self=<napari_correct_drift._core.CorrectDrift object>, t0=0, channel=0, increment=1, upsample_factor=1, roi=<napari_correct_drift._core.ROIRect object>, normalization='phase', mode='relative', max_shifts=None)
    379 def estimate_drift(
    380     self,
    381     t0: int = 0,
   (...)
    388     max_shifts: Tuple[int, int, int] = None,
    389 ):
    390     if mode == "relative":
--> 391         return self._estimate_drift_relative(
        self = <napari_correct_drift._core.CorrectDrift object at 0x000001A3DA01CFA0>
        t0 = 0
        channel = 0
        increment = 1
        upsample_factor = 1
        normalization = 'phase'
        roi = <napari_correct_drift._core.ROIRect object at 0x000001A3DA01CFD0>
        max_shifts = None
    392             t0,
    393             channel,
    394             increment,
    395             upsample_factor,
    396             normalization,
    397             roi,
    398             max_shifts,
    399         )
    401     elif mode == "absolute":
    402         return self._estimate_drift_absolute(
    403             t0,
    404             channel,
   (...)
    408             roi,
    409         )

File ~\anaconda3\envs\napari\lib\site-packages\napari_correct_drift\_core.py:477, in CorrectDrift._estimate_drift_relative(self=<napari_correct_drift._core.CorrectDrift object>, t0=1, channel=0, increment=1, upsample_factor=1, normalization='phase', roi=<napari_correct_drift._core.ROIRect object>, max_shifts=[inf, inf, inf])
    471 with warnings.catch_warnings():
    472     warnings.filterwarnings(
    473         action="ignore",
    474         category=RuntimeWarning,
    475     )
--> 477     offset, _, _ = phase_cross_correlation(
        ref_img = <class 'numpy.ndarray'> (1, 512, 1206) float32
        mov_img = <class 'numpy.ndarray'> (1, 512, 1206) float32
        upsample_factor = 1
        normalization = 'phase'
    478         ref_img,
    479         mov_img,
    480         upsample_factor=upsample_factor,
    481         return_error="always",
    482         disambiguate=True,
    483         normalization=normalization,
    484     )
    486 offset = np.asarray(offset, dtype="float32")
    488 if roi is not None:

File ~\anaconda3\envs\napari\lib\site-packages\skimage\registration\_phase_cross_correlation.py:401, in phase_cross_correlation(reference_image=<class 'numpy.ndarray'> (1, 512, 1206) float32, moving_image=<class 'numpy.ndarray'> (1, 512, 1206) float32, upsample_factor=1, space='real', disambiguate=True, return_error='always', reference_mask=None, moving_mask=None, overlap_ratio=0.3, normalization='phase')
    399         reference_image = ifftn(reference_image)
    400         moving_image = ifftn(moving_image)
--> 401     shift = _disambiguate_shift(reference_image, moving_image, shift)
        shift = <class 'numpy.ndarray'> (3,) float32
        reference_image = <class 'numpy.ndarray'> (1, 512, 1206) float32
        moving_image = <class 'numpy.ndarray'> (1, 512, 1206) float32
    403 if return_error:
    404     # Redirect user to masked_phase_cross_correlation if NaNs are observed
    405     if np.isnan(CCmax) or np.isnan(src_amp) or np.isnan(target_amp):

File ~\anaconda3\envs\napari\lib\site-packages\skimage\registration\_phase_cross_correlation.py:171, in _disambiguate_shift(reference_image=<class 'numpy.ndarray'> (1, 512, 1206) float32, moving_image=<class 'numpy.ndarray'> (1, 512, 1206) float32, shift=<class 'numpy.ndarray'> (3,) float32)
    169         max_slice = test_slice
    170 real_shift_acc = []
--> 171 for sl, pos_shift, neg_shift in zip(
        positive_shift = [0.0, 0.0, 0.0]
        negative_shift = [-1.0, -512.0, -1206.0]
        max_slice = None
    172         max_slice, positive_shift, negative_shift
    173         ):
    174     real_shift_acc.append(pos_shift if sl.stop is None else neg_shift)
    175 if not subpixel:

TypeError: 'NoneType' object is not iterable

**Comment by sommerc** [comment] 2023-10-31 09:09
Hey Toni,

thanks for giving it a try. From the error I cannot really tell what's off... Your steps look correct to me.

Would you mind sharing one of your .tif stacks? I created an upload link here:

https://seafile.ist.ac.at/u/d/63d82e4277eb4bc1b949/

Aditionally, I created the first verison of documentation. With basic steps in the Introduciton section:

https://napari-correct-drift.readthedocs.io/en/latest/

Cheers,
C

**Comment by alemanac** [comment] 2023-10-31 20:07
I've uploaded the tif stacks. Thanks for taking a look.

**Comment by sommerc** [comment] 2023-11-02 10:28
Great, thank's for sharing!

I found the issue and working on a fix.

(the stacks contain some frames which are completely 0, which causes problems downstream)

C

**Comment by alemanac** [comment] 2023-11-03 18:15
Sounds awesome! Thank you so much.

**Comment by sommerc** [comment] 2023-11-07 14:18
Dear Tony,

the latest release 0.4.0 should (technically) fix your issue. It is related to an issue in [1]

However, I was not able to register your examples. You sent me 3 stacks, where each stack is a time-point, right?

Cheers,
Chris

[1] https://github.com/scikit-image/scikit-image/issues/7089

**Comment by alemanac** [comment] 2023-11-07 18:39
Correct. Each stack is a time point.

That's strange. I'll try testing them myself. 

Thanks for the fix.

**Closed as completed** 2023-12-01 15:15 UTC
